version: '3'

services:
  db:
    #image: postgres:16.3
    image: postgres:bookworm
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: taskmanager_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
